// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GC3_trrAuBDUkOSXrG48pbQokWbjBsw',
    appId: '1:26769788686:web:a5226fc3bd29bb50ca915f',
    messagingSenderId: '26769788686',
    projectId: 'flc-10-project',
    authDomain: 'flc-10-project.firebaseapp.com',
    storageBucket: 'flc-10-project.appspot.com',
    measurementId: 'G-LSN23EXNWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5sL8aXaZXFGTQK-wP1SOd2kd12IkhM0',
    appId: '1:26769788686:android:16c5072d2def18cdca915f',
    messagingSenderId: '26769788686',
    projectId: 'flc-10-project',
    storageBucket: 'flc-10-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6yDv54V4_HXxQV-XXk89iWWVFK_CDK4',
    appId: '1:26769788686:ios:9660823cc75e4aa5ca915f',
    messagingSenderId: '26769788686',
    projectId: 'flc-10-project',
    storageBucket: 'flc-10-project.appspot.com',
    iosBundleId: 'com.studentmanagement.studentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6yDv54V4_HXxQV-XXk89iWWVFK_CDK4',
    appId: '1:26769788686:ios:abc38591bc33d7ddca915f',
    messagingSenderId: '26769788686',
    projectId: 'flc-10-project',
    storageBucket: 'flc-10-project.appspot.com',
    iosBundleId: 'com.studentmanagement.studentManagement.RunnerTests',
  );
}
